version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:17.10.0-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:11080'
        gitlab_rails['gitlab_shell_ssh_port'] = 11022
      GITLAB_ROOT_PASSWORD: 'pass1234'
    ports:
      - '11433:433'
      - '11022:22'
      - '11080:11080'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    environment:
      GITLAB_IP_ADDRESS: gitlab
    volumes:
      - '/srv/gitlab-runner/config:/etc/gitlab-runner'
      - '/var/run/docker.sock:/var/run/docker.sock'
    shm_size: '256m'

